# DestinationRule SIMPLE - Solo usa label "version"
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-microservice-keda-dr
  namespace: default
  labels:
    app: demo-microservice-keda
spec:
  host: demo-microservice-keda.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
  subsets:
    - name: stable
      labels:
        app: demo-microservice-keda
        version: stable
    - name: canary
      labels:
        app: demo-microservice-keda
        version: canary
