# VirtualService SIMPLE - Routing por header
# Header "x-test-new: true" → pods con version=canary
# Sin header → pods con version=stable

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-microservice-keda-vs
  namespace: default
  labels:
    app: demo-microservice-keda
spec:
  hosts:
    - demo-microservice-keda
  http:
    - match:
        - headers:
            x-test-new:
              exact: "true"
      route:
        - destination:
            host: demo-microservice-keda
            subset: canary
    - route:
        - destination:
            host: demo-microservice-keda
            subset: stable
