apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-microservice-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adan2804/demo-microservice.git'
    path: argocd-production
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /metadata/annotations/deployment.kubernetes.io~1revision
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
    - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt