# Argo Rollout para promociones automáticas - Opcional
# kubectl apply -f k8s/04-rollout-bluegreen.yaml

# Servicios para el rollout
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice-rollout-active
  namespace: default
  labels:
    app: demo-microservice-rollout
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: demo-microservice-rollout
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: demo-microservice-rollout-preview
  namespace: default
  labels:
    app: demo-microservice-rollout
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: demo-microservice-rollout
  type: ClusterIP

---
# Argo Rollout
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-microservice-rollout
  namespace: default
  labels:
    app: demo-microservice-rollout
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: demo-microservice-rollout-active
      previewService: demo-microservice-rollout-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  selector:
    matchLabels:
      app: demo-microservice-rollout
  template:
    metadata:
      labels:
        app: demo-microservice-rollout
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:stable
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: APP_VERSION
          value: "rollout-stable"
        - name: ENVIRONMENT
          value: "production-rollout"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10