apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-microservice-app
  namespace: argocd
  labels:
    app: demo-microservice
spec:
  project: default
  source:
    repoURL: https://github.com/tu-usuario/demo-microservice
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m