# Configuración del proxy para producción
# Tráfico normal → Rollout, Tráfico con header → Canary experiment

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config-production
  namespace: default
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream stable_backend {
            server demo-microservice-rollout-active:80;
        }
        
        upstream canary_backend {
            server demo-microservice-canary:80;
        }
        
        server {
            listen 80;
            
            location / {
                # Verificar header para canary
                if ($http_aws_cf_cd_super_svp_9f8b7a6d = "123e4567-e89b-12d3-a456-42661417400") {
                    proxy_pass http://canary_backend;
                    break;
                }
                
                # Tráfico normal va al rollout estable
                proxy_pass http://stable_backend;
                
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-production
  namespace: default
  labels:
    app: nginx-proxy-production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy-production
  template:
    metadata:
      labels:
        app: nginx-proxy-production
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-proxy-config-production

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-production
  namespace: default
  labels:
    app: nginx-proxy-production
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-proxy-production
  type: LoadBalancer