apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-v-1-0-0
  namespace: demo-app
  labels:
    app: demo-microservice
    app-version: v-1-0-0
    version: v-1-0-0
    dt-release-version: v-1-0-0
    dt-build-version: build-20251021-165623
    deployment-strategy: versioned
  annotations:
    deployment.kubernetes.io/revision: "1"
    argocd.argoproj.io/sync-wave: "2"
    version.deployment: "v-1-0-0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: demo-microservice
      app-version: v-1-0-0
  template:
    metadata:
      labels:
        app: demo-microservice
        app-version: v-1-0-0
        version: v-1-0-0
        dt-release-version: v-1-0-0
        dt-build-version: build-20251021-165623
        deployment-strategy: versioned
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
        version.pod: "v-1-0-0"
        config.checksum: "9bb738571b1aa526"
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:stable
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: APP_VERSION
          value: "v-1-0-0"
        - name: SERVICE_VERSION
          value: "v-1-0-0"
        - name: DEPLOYMENT_VERSION
          value: "v-1-0-0"
        - name: TARGET_URI
          value: "http://demo-microservice-v-1-0-0.demo-app.svc.cluster.local"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8080"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        # Variables específicas para versionado
        - name: SERVICE_NAME
          value: "demo-microservice-v-1-0-0"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 30
