apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-microservice-versioned-app
  namespace: argocd
  labels:
    app: demo-microservice-versioned
    managed-by: argocd
    sync-mode: manual
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/Adan2804/demo-microservice-config.git'
    path: k8s-versioned-manifests-processed
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: #{namespace}#
  syncPolicy:
    # SYNC MANUAL - NO automático
    # automated:
    #   prune: true
    #   selfHeal: true
    #   allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /metadata/annotations/deployment.kubernetes.io~1revision
    - /spec/replicas
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP
    - /spec/clusterIPs
    - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration