apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-production
  namespace: default
  labels:
    app: demo-microservice
    tier: production
    managed-by: azure-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-microservice
      tier: production
  template:
    metadata:
      labels:
        app: demo-microservice
        tier: production
        version: stable
        traffic-type: production
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:stable
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: APP_VERSION
          value: "production-stable"
        - name: ENVIRONMENT
          value: "production"
        - name: EXPERIMENT_ENABLED
          value: "false"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10