# Proxy inteligente y robusto
# Auto-detecta experimentos y maneja fallbacks automáticamente

# Deployment del proxy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-proxy
  namespace: default
  labels:
    app: intelligent-proxy
    tier: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intelligent-proxy
  template:
    metadata:
      labels:
        app: intelligent-proxy
        tier: infrastructure
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: health
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: nginx-config
        configMap:
          name: intelligent-proxy-config

---
# Servicio del proxy (punto de entrada único)
apiVersion: v1
kind: Service
metadata:
  name: intelligent-proxy
  namespace: default
  labels:
    app: intelligent-proxy
    tier: infrastructure
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 8080
    targetPort: 8080
    name: health
  selector:
    app: intelligent-proxy
  type: ClusterIP