# Experimento simple usando Deployment (alternativa que funciona)
# kubectl apply -f k7s/experiment-simple.yaml
# kubectl delete -f k7s/experiment-simple.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-experiment
  namespace: default
  labels:
    app: demo-microservice
    tier: experiment
    managed-by: manual-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-microservice
      tier: experiment
  template:
    metadata:
      labels:
        app: demo-microservice
        tier: experiment
        version: experimental
        traffic-type: experiment
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:experiment
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: APP_VERSION
          value: "experiment-simple-v1.1.0"
        - name: ENVIRONMENT
          value: "production-experiment"
        - name: EXPERIMENT_ENABLED
          value: "true"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10