# Deployment de producción para Istio (independiente)
# Copia de la configuración base pero con labels específicos para Istio

# Deployment de producción para Istio (independiente)
# Copia de la configuración base pero con labels específicos para Istio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-production-istio
  namespace: default
  labels:
    app: demo-microservice-istio
    tier: production
    version: stable
    managed-by: argocd
  annotations:
    # Deployment gestionado por ArgoCD - Sin auto-sync para control manual
    argocd.argoproj.io/sync-options: IgnoreExtraneous=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous

spec:
  replicas: 3
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 900
  selector:
    matchLabels:
      app: demo-microservice-istio
      tier: production
  template:
    metadata:
      labels:
        app: demo-microservice-istio
        tier: production
        traffic-type: production
        version: stable
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:stable
        imagePullPolicy: Never
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: APP_VERSION
          value: "stable-v1.0.0"
        - name: ENVIRONMENT
          value: "production"
        - name: EXPERIMENT_ENABLED
          value: "false"
        - name: ISTIO_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5