# DestinationRule - Define subsets para producción y experimento
# Basado en la documentación de Argo Rollouts + Istio

apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: demo-microservice-destination
  namespace: default
  
spec:
  host: demo-microservice-istio.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 50
        maxRequestsPerConnection: 10
    loadBalancer:
      simple: LEAST_CONN
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  # Subset para pods de producción estable (Istio)
  - name: stable
    labels:
      app: demo-microservice-istio
      tier: production
      version: stable
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 50