# ScaledObject para Escalado Garantizado Hacia Arriba (Horario de Prueba)
# Periodo: 6:00 PM - 5:00 PM (UTC-5, Colombia) - Todo el día excepto 5PM-6PM
# Lógica: Garantiza mínimo 3 pods SIEMPRE fuera del horario de downscale
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demo-microservice-intelligent-upscale
  namespace: default
  labels:
    app: demo-microservice-istio
    scaling-strategy: intelligent-upscale
    managed-by: argocd
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
    description: "Escalado de prueba garantizado - asegura 3 pods fuera de 5:10PM-6PM"
spec:
  scaleTargetRef:
    name: demo-microservice-production-istio
  
  # Configuración de réplicas para horario laboral
  minReplicaCount: 3      # Mínimo garantizado: 3 pods en horario laboral
  maxReplicaCount: 10     # Máximo durante el día: puede escalar hasta 10 si hay demanda
  
  # Política de escalado: garantiza capacidad desde el primer minuto
  pollingInterval: 30     # Evalúa cada 30 segundos
  cooldownPeriod: 60      # Espera solo 1 minuto antes de escalar (respuesta rápida)
  
  triggers:
    # Trigger 1: Horario de prueba (6:00 PM - 5:10 PM del día siguiente)
    # Activo todo el día EXCEPTO durante 5:10PM-6PM
    - type: cron
      metadata:
        timezone: "America/Bogota"      # UTC-5 (Colombia)
        start: "0 18 * * *"              # 6:00 PM - Inicia horario de upscale
        end: "15 17 * * *"               # 5:10 PM - Termina horario de upscale
        desiredReplicas: "3"             # Objetivo: mínimo 3 pods SIEMPRE
    
    # Trigger 2: Escalado adicional por CPU (si hay picos de demanda)
    # Escala más allá de 3 pods si la carga aumenta
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"                      # Escala hacia arriba si CPU > 70%
    
    # Trigger 3: Escalado adicional por Memoria (si hay picos de demanda)
    - type: memory
      metricType: Utilization
      metadata:
        value: "70"                      # Escala hacia arriba si Memoria > 70%
  
  # Configuración avanzada del HPA generado
  advanced:
    horizontalPodAutoscalerConfig:
      name: demo-microservice-intelligent-upscale-hpa
      behavior:
        scaleUp:
          # Política agresiva: escala rápidamente hacia arriba
          stabilizationWindowSeconds: 0      # Sin espera para escalar hacia arriba
          policies:
            - type: Pods
              value: 3                       # Puede agregar hasta 3 pods a la vez
              periodSeconds: 60              # Cada minuto
            - type: Percent
              value: 50                      # O 50% de las réplicas actuales
              periodSeconds: 60
          selectPolicy: Max                  # Usa la política más agresiva
        
        scaleDown:
          # Política conservadora: escala lentamente hacia abajo
          # Pero nunca por debajo de 3 pods durante horario laboral
          stabilizationWindowSeconds: 300    # Espera 5 minutos de estabilidad
          policies:
            - type: Pods
              value: 1                       # Reduce máximo 1 pod a la vez
              periodSeconds: 180             # Cada 3 minutos
          selectPolicy: Min                  # Usa la política más conservadora

---
# ConfigMap con información del escalado diurno
apiVersion: v1
kind: ConfigMap
metadata:
  name: intelligent-upscale-config
  namespace: default
  labels:
    app: demo-microservice-istio
    scaling-strategy: intelligent-upscale
data:
  description: |
    ScaledObject para Escalado Garantizado Hacia Arriba (PRUEBA)
    
    Periodo Activo: 6:00 PM - 5:10 PM (UTC-5, Colombia)
    Todo el día EXCEPTO 5:10PM-6PM
    
    Comportamiento:
    - A las 6:00 PM, garantiza mínimo 3 pods de forma inmediata
    - No evalúa métricas para el mínimo: SIEMPRE 3 pods
    - Restaura la capacidad después del periodo de downscale
    
    - Durante el periodo activo, puede escalar más allá de 3 pods si:
      * CPU > 70%
      * Memoria > 70%
      * Responde rápidamente a picos de demanda
    
    - Puede escalar hasta 10 pods si la demanda lo requiere
    - Escala hacia abajo lentamente (conservador)
    - Nunca baja de 3 pods durante el periodo activo
    
    Garantía de Rendimiento:
    - Capacidad mínima asegurada a las 6:00 PM
    - Sin esperar a que las métricas se disparen
    - Cumplimiento de SLA garantizado
  
  timezone: "America/Bogota"
  active-hours: "18:00 - 17:10"
  min-replicas: "3"
  max-replicas: "10"
  cpu-scale-threshold: "70%"
  memory-scale-threshold: "70%"
  cooldown-period: "60s"
