apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-microservice-production-istio
  namespace: default
  labels:
    app: demo-microservice-istio
    tier: production
    version: stable
    managed-by: istio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-microservice-istio
      tier: production
  template:
    metadata:
      labels:
        app: demo-microservice-istio
        tier: production
        traffic-type: production
        version: stable
        sidecar.istio.io/inject: "true"  # Inyección automática de Istio sidecar
    spec:
      containers:
      - name: demo-microservice
        image: demo-microservice:stable
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: APP_VERSION
          value: "production-stable-istio"
        - name: ENVIRONMENT
          value: "production-istio"
        - name: EXPERIMENT_ENABLED
          value: "false"
        - name: ISTIO_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5