apiVersion: v1
kind: ConfigMap
metadata:
  name: security-filters-config
  namespace: #{namespace}#
  labels:
    app: security-filters
    component: configuration
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  TARGET_URI: "http://demo-microservice.#{namespace}#.svc.cluster.local"
  GATEWAY_PORT: "8080"
  MANAGEMENT_PORT: "8081"
  ROUTES_JSON: |
    {
      "routes": [
        {
          "id": "demo-microservice-route",
          "uri": "http://demo-microservice.#{namespace}#.svc.cluster.local",
          "predicates": [
            {
              "name": "Path",
              "args": {
                "pattern": "/demo/**"
              }
            },
            {
              "name": "Method",
              "args": {
                "methods": "GET,POST"
              }
            }
          ],
          "filters": [
            {
              "name": "RemoveRequestHeader",
              "args": {
                "name": "X-Internal-Token"
              }
            },
            {
              "name": "AddResponseHeader",
              "args": {
                "name": "X-Gateway-Version",
                "value": "#{version}#"
              }
            },
            {
              "name": "AddResponseHeader",
              "args": {
                "name": "X-Routed-By",
                "value": "security-filters"
              }
            },
            {
              "name": "AddResponseHeader",
              "args": {
                "name": "X-Target-Service",
                "value": "demo-microservice"
              }
            },
            {
              "name": "StripPrefix",
              "args": {
                "parts": 0
              }
            }
          ],
          "metadata": {
            "connect-timeout": 5000,
            "response-timeout": 30000
          }
        },
        {
          "id": "health-check-route",
          "uri": "http://demo-microservice.#{namespace}#.svc.cluster.local",
          "predicates": [
            {
              "name": "Path",
              "args": {
                "pattern": "/health"
              }
            }
          ],
          "filters": [
            {
              "name": "AddResponseHeader",
              "args": {
                "name": "X-Health-Check",
                "value": "gateway-proxied"
              }
            }
          ]
        }
      ],
      "default_filters": [
        {
          "name": "AddResponseHeader",
          "args": {
            "name": "X-Gateway-Timestamp",
            "value": "#{timestamp}#"
          }
        },
        {
          "name": "AddResponseHeader",
          "args": {
            "name": "X-Request-ID",
            "value": "#{request_id}#"
          }
        }
      ],
      "global_cors": {
        "allowed_origins": ["*"],
        "allowed_methods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        "allowed_headers": ["*"],
        "allow_credentials": false,
        "max_age": 3600
      }
    }
  SECURITY_CONFIG: |
    security:
      enabled: true
      rate_limiting:
        enabled: true
        requests_per_minute: 1000
      authentication:
        required: false
        jwt_validation: false
      headers:
        x_frame_options: DENY
        x_content_type_options: nosniff
        x_xss_protection: "1; mode=block"
        strict_transport_security: "max-age=31536000; includeSubDomains"
  LOGGING_CONFIG: |
    logging:
      level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web: INFO
        com.demo.security: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"