spring:
  application:
    name: demo-microservice
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT:8080}

# Custom application properties
app:
  version: ${APP_VERSION:v-1-0-0}
  target-uri: ${TARGET_URI:}
  
logging:
  level:
    com.demo: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: production
      
logging:
  level:
    root: INFO
    com.demo: INFO
    
management:
  endpoint:
    health:
      show-details: when-authorized

---
spring:
  config:
    activate:
      on-profile: development
      
logging:
  level:
    root: DEBUG
    com.demo: DEBUG
    org.springframework.web: DEBUG